#!/bin/bash -e
cat <<EOF
This is the lighttpd-centos7 S2I image:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:

s2i build https://github.com/hector-vido/sti-lighttpd.git lighttpd-centos7 lighttpd-ex

You can then run the resulting image via:
docker run -p 8080:8080 lighttpd-ex
EOF
